#MAJOR 2

***### BAG OF WORDS ###***

In [0]:
!pip install pickle

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle


In [0]:
#mount the drive to colab

from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
#checking the usage of gpus by colab

from keras import backend as K
K.tensorflow_backend._get_available_gpus()

Using TensorFlow backend.


['/job:localhost/replica:0/task:0/device:GPU:0']

In [0]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 3032150613692309798
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 14233700690669714090
physical_device_desc: "device: XLA_CPU device"
, name: "/device:XLA_GPU:0"
device_type: "XLA_GPU"
memory_limit: 17179869184
locality {
}
incarnation: 98966261963422908
physical_device_desc: "device: XLA_GPU device"
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 15956161332
locality {
  bus_id: 1
  links {
  }
}
incarnation: 13603419413933170078
physical_device_desc: "device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0"
]


importing the libraries

In [0]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.linear_model import LogisticRegression as LR

importing and splitting the dataset into train and test

In [0]:
from sklearn.model_selection import train_test_split

#%% handlig the dataset with classes with less than 7000 instances each
s
dataset=dataset.dropna()
X=dataset['text_instance']
y=dataset['category']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)


vectorising the data samples and fitting a  model




In [0]:
print("Vectorizing train...")

vectorizer = TfidfVectorizer( max_features = 40000, ngram_range = ( 1, 3 ), 
	sublinear_tf = True )
train_x = vectorizer.fit_transform( X_train )

print("Vectorizing test...")

test_x = vectorizer.transform( X_test)

print("Training...")



Vectorizing train...
Vectorizing test...
Training...


fitting the model

In [0]:

# using a simple logistic regression model to fit through the dataset
model = LR()
model.fit( train_x, y_train )


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

predicting from the model

In [0]:
p = model.predict_proba( test_x )[:,1] 
y_pred=model.predict(test_x)

In [0]:
from sklearn.metrics import accuracy_score
print("Accuracy score: ",str(accuracy_score(y_test, y_pred)))



Accuracy score:  0.5340258071424747


#53.4% accuracy achieved with BOW 

In [0]:
import pickle 

# Save the trained model as a pickle string. 
# saved_model = pickle.dumps(model,"model_BOW_less7000_25classes") 

pickle.dump(model, open("model_BOW_less7000_25classes.sav", 'wb'))


In [0]:
y_pred[:5]

array(['MEDIA', 'DIVORCE', 'RELIGION', 'WEIRD NEWS', 'MONEY'],
      dtype=object)

In [0]:
y_test[:5]

5046          MEDIA
90699       DIVORCE
30914     WORLDPOST
43396    WEIRD NEWS
17987         STYLE
Name: category, dtype: object

In [0]:
X_test[:5]

5046     Woman's Elaborate Scheme To Discredit Washingt...
90699    Why Dating And Men Are Better When You're A Si...
30914    Rome is Berning! The Bromance Between Bernie a...
43396             Covered Wagon Turns Over, Snarls Traffic
17987                           No need to break the bank.
Name: text_instance, dtype: object

In [0]:
from google.colab import drive
drive.mount('/content/drive')

#Bag of words validate

code to increase the allotted ram from 12GB to 25GB

In [0]:
while(1):
    pass

In [0]:
import os
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression as LR
from sklearn.metrics import roc_auc_score as AUC

In [0]:
data_file = "/content/drive/My Drive/MAJOR 2- WORK IN PROGRESS/dataset_25classes_less7000.csv"

data = pd.read_csv( data_file)
data=data.dropna()

preprocess the dataset

In [0]:
print(data.shape)

print(data.columns)
print(data['category'].unique())
print()
print(data['category'].value_counts())

(93384, 3)
Index(['Unnamed: 0', 'text_instance', 'category'], dtype='object')
['CRIME' 'WORLD NEWS' 'IMPACT' 'WEIRD NEWS' 'WOMEN' 'MEDIA' 'TECH'
 'RELIGION' 'SCIENCE' 'LATINO VOICES' 'EDUCATION' 'COLLEGE'
 'ARTS & CULTURE' 'STYLE' 'GREEN' 'TASTE' 'GOOD NEWS' 'WORLDPOST' 'FIFTY'
 'ARTS' 'DIVORCE' 'MONEY' 'ENVIRONMENT' 'CULTURE & ARTS']

DIVORCE           6852
WOMEN             6592
IMPACT            6520
CRIME             6080
MEDIA             5088
WEIRD NEWS        4879
GREEN             4668
RELIGION          4413
WORLD NEWS        4352
TECH              4163
TASTE             4036
SCIENCE           3953
STYLE             3821
WORLDPOST         3820
MONEY             3413
ARTS & CULTURE    2678
ENVIRONMENT       2644
FIFTY             2443
GOOD NEWS         2437
ARTS              2372
LATINO VOICES     2150
COLLEGE           2065
CULTURE & ARTS    2049
EDUCATION         1896
Name: category, dtype: int64


In [0]:
# after analysing the classses: combining some of the spearate classes into one


#weird new + world news + good news= news
#CULTURE & ARTS + ARTS & CULTURE == ARTS & CULTURE
#tech + science = science and tech
#green+environment= environment
#REMOVE LATINO VOICES AND FIFTY
#college +education = education & college


data['category'].replace({"COLLEGE":"COLLEGE & EDUCATION","EDUCATION":"COLLEGE & EDUCATION",
                          "GREEN":"ENVIRONMENT","TECH":"TECH & SCIENCE","SCIENCE":"TECH & SCIENCE",
                          "CULTURE & ARTS":"ARTS & CULTURE","WEIRD NEWS":"NEWS","GOOD NEWS":"NEWS","WORLD NEWS":"NEWS","ARTS":"ARTS & CULTURE"}, inplace=True)

removed_classes=["LATINO VOICES","FIFTY"]
data=data[~data['category'].isin(removed_classes)]


In [0]:
print(len(data['category'].unique()))
print(data['category'].value_counts())

15
NEWS                   11668
TECH & SCIENCE          8116
ENVIRONMENT             7312
ARTS & CULTURE          7099
DIVORCE                 6852
WOMEN                   6592
IMPACT                  6520
CRIME                   6080
MEDIA                   5088
RELIGION                4413
TASTE                   4036
COLLEGE & EDUCATION     3961
STYLE                   3821
WORLDPOST               3820
MONEY                   3413
Name: category, dtype: int64


In [0]:
data_original=data.copy()
train_i_original, test_i_original = train_test_split( np.arange( len( data_original )), train_size = 0.8, random_state = 44 )

In [0]:
print(data_original.head(2))

   Unnamed: 0                                      text_instance category
0           0  There Were 2 Mass Shootings In Texas Last Week...    CRIME
1           1  She left her husband. He killed their children...    CRIME


In [0]:
factor = pd.factorize(data['category'])
data.category = factor[0]
definitions = factor[1]


print(len(factor))
print(factor)

2
(array([0, 0, 1, ..., 5, 5, 5]), Index(['CRIME', 'NEWS', 'IMPACT', 'WOMEN', 'MEDIA', 'TECH & SCIENCE',
       'RELIGION', 'COLLEGE & EDUCATION', 'ARTS & CULTURE', 'STYLE',
       'ENVIRONMENT', 'TASTE', 'WORLDPOST', 'DIVORCE', 'MONEY'],
      dtype='object'))


In [0]:
print(data.category[:5])
print(definitions)
print(len(definitions))
print(data.category[:5])

0    0
1    0
2    1
3    1
4    2
Name: category, dtype: int64
Index(['CRIME', 'NEWS', 'IMPACT', 'WOMEN', 'MEDIA', 'TECH & SCIENCE',
       'RELIGION', 'COLLEGE & EDUCATION', 'ARTS & CULTURE', 'STYLE',
       'ENVIRONMENT', 'TASTE', 'WORLDPOST', 'DIVORCE', 'MONEY'],
      dtype='object')
15
0    0
1    0
2    1
3    1
4    2
Name: category, dtype: int64


In [0]:
print(data.head())

   Unnamed: 0                                      text_instance  category
0           0  There Were 2 Mass Shootings In Texas Last Week...         0
1           1  She left her husband. He killed their children...         0
2          22  South Korean President Meets North Korea's Kim...         1
3          23  The two met to pave the way for a summit betwe...         1
4          24  With Its Way Of Life At Risk, This Remote Oyst...         2


In [0]:
print(len(data['category'].unique()))

15


In [0]:
train_i, test_i = train_test_split( np.arange( len( data )), train_size = 0.8, random_state = 44 )

In [0]:
print(train_i.shape)
print(test_i.shape)


print(train_i_original.shape)
print(test_i_original.shape)

(71032,)
(17759,)
(71032,)
(17759,)


In [0]:
print(train_i[:2])
print(train_i_original[:2])

[86120 13936]
[86120 13936]


In [0]:
train_i[:5]
print(train_i[1])
print(data.iloc[train_i[1]])

print(train_i_original[1])
print(data_original.iloc[train_i_original[1]])

13936
Unnamed: 0                                                   53882
text_instance    Billionaire Cash Is Flooding Los Angeles To Pu...
category                                                         7
Name: 14496, dtype: object
13936
Unnamed: 0                                                   53882
text_instance    Billionaire Cash Is Flooding Los Angeles To Pu...
category                                       COLLEGE & EDUCATION
Name: 14496, dtype: object


In [0]:
train = data.iloc[train_i]
test = data.iloc[test_i]

train=train.dropna()
test=test.dropna()

In [0]:
print(test[:5])

       Unnamed: 0                                      text_instance  category
50646      181646           China Making Some Missiles More Powerful        12
33658      132224  Richard Branson Returns To Passenger Space Tra...         5
33922      133194  Homeless Shelter Pods Provide Night's Rest, Ca...         2
93383      348444  Mitt Romney's Project ORCA Failure: Broken ORC...         5
63119      210174  What Happens When 5 Street Artists Share A Wal...         8


In [0]:
print(train.shape)
print(test.shape)

print(train.columns)

(71032, 3)
(17759, 3)
Index(['Unnamed: 0', 'text_instance', 'category'], dtype='object')


In [0]:
print("Creating the bag of words...\n")

vectorizer = CountVectorizer( analyzer = "word", tokenizer = None, preprocessor = None, 
	stop_words = None, max_features = 5000 )


Creating the bag of words...



In [0]:
train_data_features = vectorizer.fit_transform(train['text_instance'])
train_data_features = train_data_features.toarray()


In [0]:
print(len(train_data_features))

71032


In [0]:
print(type(train_data_features))

print(train_data_features[:5])

print(len(train_data_features[0]))

print(np.unique(train_data_features[:5]))

<class 'numpy.ndarray'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
5000
[0 1 2]


In [0]:
# # test features

# # Create an empty list and append the clean reviews one by one
# clean_test_reviews = []

# print("Cleaning and parsing the test set movie reviews...\n")

# skip=0
# for review in test['text_instance']:
#     try:
#         clean_test_reviews.append( " ".join( KaggleWord2VecUtility.review_to_wordlist( review, True )))
#     except:
#         skip+=1
# print(skip)


In [0]:
#%%
# Get a bag of words for the test set, and convert to a numpy array
test_data_features = vectorizer.transform( test['text_instance'] )
test_data_features = test_data_features.toarray()



In [0]:
#%%
###

print("Training the random forest (this may take a while)...")

forest = RandomForestClassifier( n_estimators = 100, n_jobs = -1, verbose = 1 )
forest = forest.fit( train_data_features, train["category"] )


Training the random forest (this may take a while)...


[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  4.3min
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:  9.2min finished


In [0]:
# saving the model for further use in the future after the session expires??
import pickle

pickle.dump(forest, open("model_BOW_RF_less7000_24classes_REFINED.pkl", 'wb'))


In [0]:
#importing the model to use
import pickle 

filename="/content/drive/My Drive/MAJOR 2- WORK IN PROGRESS/model_BOW_RF_less7000_24classes_REFINED.pkl"
fileopen=open(filename,"rb")
forest=pickle.load(fileopen)

In [0]:


import os

newpath="/content/model_BOW_RF_less7000_24classes_REFINED.pkl"
filename=newpath

import pickle
fileopen=open(filename,"rb")
model=pickle.load(fileopen)

In [0]:
pickle.dump(model,open("/content/drive/My Drive/MAJOR 2- WORK IN PROGRESS/model_BOW_RF_less7000_24classes_REFINED.pkl","wb"))

In [0]:
forest=model
print("Predicting test labels...\n")
rf_p = forest.predict_proba( test_data_features )




Predicting test labels...



[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  46 tasks      | elapsed:    1.6s
[Parallel(n_jobs=2)]: Done 100 out of 100 | elapsed:    3.4s finished


In [0]:
print(type(rf_p))
print(rf_p[0,1])

<class 'numpy.ndarray'>
0.1106031746031746


In [0]:
print(rf_p[:5])

[[0.         0.11060317 0.         0.02       0.08       0.02
  0.         0.06       0.03       0.         0.06527778 0.04
  0.01       0.03       0.01       0.04771825 0.         0.13
  0.02       0.         0.0360119  0.16038889 0.03       0.1       ]
 [0.02       0.01       0.01       0.04       0.02       0.03
  0.         0.01       0.         0.01       0.02       0.04
  0.         0.03       0.01       0.57       0.03       0.03
  0.         0.01       0.01       0.04       0.04       0.02      ]
 [0.         0.         0.         0.         0.         0.
  0.         0.01       0.         0.         0.03       0.
  0.         0.         0.         0.         0.92       0.
  0.         0.         0.04       0.         0.         0.        ]
 [0.         0.01       0.         0.01       0.         0.01
  0.01       0.         0.         0.         0.08       0.
  0.02       0.43       0.         0.01       0.         0.
  0.         0.         0.09       0.02       0.3        0.

In [0]:
print(np.argmax(rf_p[0]))   #finding the index of the maximum entry of the numpy array so as to map back to the original class

21


In [0]:
#in the abovce output, each ofthe instance has been classified into 24 classes 
# to chekc if the distribution is sigmodial in fashio i.e sum=1

print(np.sum(rf_p[0]))

1.0


In [0]:
#to find the class of the predicted instances

#find the index of the maximum element from the numpy array
#create a hashmap or simple map to map all the classes to the index numbers 

#once the whole dictionry is fromed

#run through each of the predicted instance and find the maximumm element along witht he probalility saved separately in a list

#combine the results from both the y_pred and y_test_original to match and finally find the accuracy of the model


reversefactor = dict(zip(range(24),definitions))
# y_test = np.vectorize(reversefactor.get)(test['category'])


category_index=[]
for i in rf_p:
    index=np.argmax(i)
    category_index.append(index)


y_pred = np.vectorize(reversefactor.get)(category_index)


In [0]:
print(reversefactor)

{0: 'CRIME', 1: 'WORLD NEWS', 2: 'IMPACT', 3: 'WEIRD NEWS', 4: 'WOMEN', 5: 'MEDIA', 6: 'TECH', 7: 'RELIGION', 8: 'SCIENCE', 9: 'LATINO VOICES', 10: 'EDUCATION', 11: 'COLLEGE', 12: 'ARTS & CULTURE', 13: 'STYLE', 14: 'GREEN', 15: 'TASTE', 16: 'GOOD NEWS', 17: 'WORLDPOST', 18: 'FIFTY', 19: 'ARTS', 20: 'DIVORCE', 21: 'MONEY', 22: 'ENVIRONMENT', 23: 'CULTURE & ARTS'}


In [0]:
print(y_test[:5])

print(category_index[:5])

print(y_pred[:5])

[None None None None None]
[21, 15, 16, 13, 18]
['MONEY' 'TASTE' 'GOOD NEWS' 'STYLE' 'FIFTY']


In [0]:
print(pd.crosstab(test['category'], y_pred, rownames=['Actual class'], colnames=['Predicted class']))


Predicted class  ARTS  ARTS & CULTURE  COLLEGE  ...  WOMEN  WORLD NEWS  WORLDPOST
Actual class                                    ...                              
ARTS               10               0       48  ...     30          38         27
ARTS & CULTURE     15               3       36  ...     17          73         34
COLLEGE             8               1       30  ...      1           3          5
CRIME              11               3       46  ...      7           1         11
CULTURE & ARTS      3               1       27  ...    115          11         16
DIVORCE            17               2       41  ...      3           4         15
EDUCATION           7               2       42  ...      0           1          6
ENVIRONMENT         9               2       57  ...     10           4          9
FIFTY               9               3       55  ...      3           4         15
GOOD NEWS           9               2       53  ...      3           9         29
GREEN           

In [0]:
#finding the accuracy of the model

correct=0
total=len(test['category'])
skipped=0

for i in range(0,len(y_pred)):
    try:
        if y_pred[i]==test['category'][i]:
            correct+=1
    except:
        skipped+=1


print("number of skipped instances: ",skipped)


accuracy=correct/total

print("the accuracy of the model is found out to be: ",accuracy)
print(correct)

number of skipped instances:  14989
the accuracy of the model is found out to be:  0.006585640092091878
123


In [0]:
auc = AUC( test['category'].values, rf_p[:,1] )
print("random forest AUC:", auc)

# a random score from a _random_ forest
# AUC: 0.919056767104


ValueError: ignored

In [0]:
#%%
# let's define a helper function

def train_and_eval_auc( model, train_x, train_y, test_x, test_y ):
	model.fit( train_x, train_y )
	p = model.predict_proba( test_x )
	auc = AUC( test_y, p[:,1] )
	return auc

#

lr = LR()
auc = train_and_eval_auc( lr, train_data_features, train["sentiment"], \
	test_data_features, test["sentiment"].values )
print("logistic regression AUC:", auc)

# logistic regression AUC: 0.925748792247
# logistic regression AUC: 0.928301070895	# different split


# train a random forest ten times, average the scores

rf_aucs = []
for i in range( 10 ):
	auc = train_and_eval_auc( forest, train_data_features, train["sentiment"], \
		test_data_features, test["sentiment"].values )
	
	print("random forest run {}, AUC: {}".format( i, auc ))
	rf_aucs.append( auc )
	
avg_auc = sum( rf_aucs ) / len( rf_aucs )
print("Average AUC from random forest:", avg_auc)



#part 3 of bag of words

***improved BOW validation script***
***changes: leave stopwords in, use TF-IDF vectorizer, removed converting vectorizer output to np.array***


In [0]:
# importing the libraries
import os
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression as LR
from sklearn.metrics import roc_auc_score as AUC



In [0]:
data_file = '/content/drive/My Drive/MAJOR 2- WORK IN PROGRESS/dataset_25classes_less7000.csv'
data = pd.read_csv( data_file )

train_i, test_i = train_test_split( np.arange( len( data )), train_size = 0.8, random_state = 44 )

train = data.ix[train_i]
test = data.ix[test_i]

In [0]:
#handling the preprocessing of the imported data file once again

print(data.shape)
print(data['category'].value_count())


#removing the classes and combining some into a single class 

# after analysing the classses: combining some of the spearate classes into one


#weird new + world news + good news= news
#CULTURE & ARTS + ARTS & CULTURE == ARTS & CULTURE
#tech + science = science and tech
#green+environment= environment
#REMOVE LATINO VOICES AND FIFTY
#college +education = education & college


data['category'].replace({"COLLEGE":"COLLEGE & EDUCATION","EDUCATION":"COLLEGE & EDUCATION",
                          "GREEN":"ENVIRONMENT","TECH":"TECH & SCIENCE","SCIENCE":"TECH & SCIENCE",
                          "CULTURE & ARTS":"ARTS & CULTURE","WEIRD NEWS":"NEWS","GOOD NEWS":"NEWS","WORLD NEWS":"NEWS","ARTS":"ARTS & CULTURE"}, inplace=True)

removed_classes=["LATINO VOICES","FIFTY"]
data=data[~data['category'].isin(removed_classes)]

data_original=data.copy()
train_i_original, test_i_original = train_test_split( np.arange( len( data_original )), train_size = 0.8, random_state = 44 )

## factorize the category column of the dataset as a part of one hot encoding

factor = pd.factorize(data['category'])
data.category = factor[0]
definitions = factor[1]


print(len(factor))
print(factor)

#slitting the dataset into train and test dataset , first using the index of the instances and the allocating the rows to the defined dataset

train_i, test_i = train_test_split( np.arange( len( data )), train_size = 0.8, random_state = 44 )

train = data.iloc[train_i]
test = data.iloc[test_i]

train=train.dropna()
test=test.dropna()

In [0]:
# factorize the category column of the dataset 

print("Vectorizing...")

vectorizer = TfidfVectorizer( max_features = 40000, ngram_range = ( 1, 3 ), 
	sublinear_tf = True )

train_data_features = vectorizer.fit_transform( train )
test_data_features = vectorizer.transform( train )






In [0]:
#fitting the model and predicting and finding the accuracy of the model


lr = LR()

lr.fit(train['test_instance'],train['category'])
p=lr.predict(test['test_instance'])


import keras

accuracy=keras.metrics.categorical_accuracy(test['category'], p)



#part 4: bag of words


fofe remaining

In [0]:
import os
import pandas as pd
import numpy as np

from sklearn.cross_validation import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression as LR
from sklearn.metrics import roc_auc_score as AUC


https://wiki.eecs.yorku.ca/lab/MLL/projects:fofe:start

fofe information